- name: Sending notification email        
  mail:
    host: "{{ email_host }}"
    port: "{{ email_port }}"
    username: "{{ email_username }}"
    password: "{{ email_password }}"
    from: "{{ email_username }}"
    subtype: html
    attach:
    - /tmp/ntt-logo.PNG
    to:
    - rodel.paco@webserverpage.com
    - rodel.paco@global.ntt
    subject: MSSQL Provisioning Report
    body: >-
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          * {
            -moz-box-sizing: border-box;
            -webkit-box-sizing: border-box;
            box-sizing: border-box;
          }

          html {
            font-family: Arial, Helvetica, sans-serif;
            color: #37474f;
          }

          body {
            margin: 0px;
            background-color: #eee;
          }

          h1,
          h2 {
            text-align: center;
          }

          table {
            border-spacing: 0;
            width: 100%;
          }

          table thead th {
            font-size: 14px;
            font-weight: bold;
            padding: 16px;
            background-color: #37474f;
            color: white;
            text-align: left;
          }

          .bordered-cell {
            font-size: 13px;
            border-bottom: 1px solid #cfd8dc;
            background-color: #fff;
            padding: 8px 16px;
          }

          .heading {
            padding: 16px;
            color: #fff;
            background-color: #0033cc;
          }

          .heading__title {
            display: flex;
            align-items: center;
            justify-content: center;
            margin-left: -140px;
          }
          .heading__img {
            margin-right: 40px;
          }
          .report-container {
            max-width: 650px;
            margin: auto;
          }
        </style>
      </head>
      <body>
        <section class="report-container">
          <div class="heading">
            <div class="heading__title">
              <img width="100px" class="heading__img" src="ntt-logo.PNG" alt="" />
              <h1>MSSQL Provisioning Report</h1>
            </div>
            <h2>Hostname: {{ ansible_hostname }}</h2>
          </div>
          <table>
            <thead>
              <tr>
                <th>OS Version</th>
                <th>vCPU</th>
                <th>Total Memory (mb)</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td class="bordered-cell">{{ ansible_os_name }}</td>
                <td class="bordered-cell">{{ ansible_processor_vcpus }}</td>
                <td class="bordered-cell">{{ ansible_memtotal_mb }}</td>
              </tr>
            </tbody>
          </table>
          <table>
            <thead>
              <tr>
                <th>Windows Domain</th>
                <th>Domain Role</th>
                <th>Host FQDN</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td class="bordered-cell">{{ ansible_windows_domain }}</td>
                <td class="bordered-cell">{{ ansible_windows_domain_role }}</td>
                <td class="bordered-cell">{{ ansible_fqdn }}</td>
              </tr>
            </tbody>
          </table>
          <table>
            <thead>
              <tr>
                <th>Interface(s)</th>
                <th>IP Address</th>
                <th>Gateway</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td class="bordered-cell">{{ ansible_interfaces }}</td>
                <td class="bordered-cell">{{ ansible_ip_addresses }}</td>
                <td class="bordered-cell">{{ ansible_interfaces['default_gateway'] }}</td>
              </tr>
            </tbody>
          </table>
        </section>
      </body>
      </html>
    secure: starttls
  delegate_to: localhost