- name: Sending email
  hosts: device_roles_db-tier
  vars:
    check_group_names:
      - device_roles_db-tier
  ignore_errors: true
  ignore_unreachable: true
  roles:
    - linux-send-email
  become: yes